// Code generated by protoc-gen-go.
// source: msg.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	msg.proto
	rpc.proto

It has these top-level messages:
	RpcServerStatus
	RpcHeartRequest
	RpcHeartRespose
	RpcGetServerInfoByType
	RpcRequest
	RpcResponse
	RpcHeart
	RpcRouterItem
	RpcRouter
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 3秒上传一次到center服务器
type RpcServerStatus struct {
	Addr             *string `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
	Load             *int32  `protobuf:"varint,2,opt,name=load" json:"load,omitempty"`
	Sid              *int32  `protobuf:"varint,3,opt,name=sid" json:"sid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RpcServerStatus) Reset()                    { *m = RpcServerStatus{} }
func (m *RpcServerStatus) String() string            { return proto.CompactTextString(m) }
func (*RpcServerStatus) ProtoMessage()               {}
func (*RpcServerStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RpcServerStatus) GetAddr() string {
	if m != nil && m.Addr != nil {
		return *m.Addr
	}
	return ""
}

func (m *RpcServerStatus) GetLoad() int32 {
	if m != nil && m.Load != nil {
		return *m.Load
	}
	return 0
}

func (m *RpcServerStatus) GetSid() int32 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

type RpcHeartRequest struct {
	Version          *uint32          `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Status           *RpcServerStatus `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *RpcHeartRequest) Reset()                    { *m = RpcHeartRequest{} }
func (m *RpcHeartRequest) String() string            { return proto.CompactTextString(m) }
func (*RpcHeartRequest) ProtoMessage()               {}
func (*RpcHeartRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RpcHeartRequest) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *RpcHeartRequest) GetStatus() *RpcServerStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type RpcHeartRespose struct {
	Version          *uint32            `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	StatusList       []*RpcServerStatus `protobuf:"bytes,2,rep,name=statusList" json:"statusList,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *RpcHeartRespose) Reset()                    { *m = RpcHeartRespose{} }
func (m *RpcHeartRespose) String() string            { return proto.CompactTextString(m) }
func (*RpcHeartRespose) ProtoMessage()               {}
func (*RpcHeartRespose) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RpcHeartRespose) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *RpcHeartRespose) GetStatusList() []*RpcServerStatus {
	if m != nil {
		return m.StatusList
	}
	return nil
}

type RpcGetServerInfoByType struct {
	Rid              *uint32 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	Err              *string `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	Data             []byte  `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RpcGetServerInfoByType) Reset()                    { *m = RpcGetServerInfoByType{} }
func (m *RpcGetServerInfoByType) String() string            { return proto.CompactTextString(m) }
func (*RpcGetServerInfoByType) ProtoMessage()               {}
func (*RpcGetServerInfoByType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RpcGetServerInfoByType) GetRid() uint32 {
	if m != nil && m.Rid != nil {
		return *m.Rid
	}
	return 0
}

func (m *RpcGetServerInfoByType) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

func (m *RpcGetServerInfoByType) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*RpcServerStatus)(nil), "pb.RpcServerStatus")
	proto.RegisterType((*RpcHeartRequest)(nil), "pb.RpcHeartRequest")
	proto.RegisterType((*RpcHeartRespose)(nil), "pb.RpcHeartRespose")
	proto.RegisterType((*RpcGetServerInfoByType)(nil), "pb.RpcGetServerInfoByType")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0xd0, 0xb1, 0x4b, 0xc5, 0x30,
	0x10, 0x06, 0x70, 0xde, 0xeb, 0x53, 0xe9, 0xbd, 0x4a, 0x21, 0x82, 0x14, 0x27, 0xa9, 0x83, 0x4e,
	0x1d, 0x1c, 0x9d, 0xa4, 0x4b, 0x15, 0x9d, 0x5a, 0x27, 0xb7, 0xb4, 0x39, 0xa5, 0xa0, 0x4d, 0xbc,
	0xbb, 0x0a, 0xfd, 0xef, 0x4d, 0x93, 0x45, 0x94, 0x37, 0x7e, 0x07, 0xf7, 0xcb, 0x77, 0x81, 0xf4,
	0x93, 0xdf, 0x2b, 0x47, 0x56, 0xac, 0xda, 0xba, 0xfe, 0x22, 0x25, 0x37, 0xc4, 0x58, 0xde, 0x41,
	0xde, 0xba, 0xa1, 0x43, 0xfa, 0x46, 0xea, 0x44, 0xcb, 0xcc, 0x2a, 0x83, 0x9d, 0x36, 0x86, 0x8a,
	0xcd, 0xe5, 0xe6, 0x26, 0x5d, 0xd3, 0x87, 0xd5, 0xa6, 0xd8, 0xfa, 0x74, 0xa4, 0xf6, 0x90, 0xf0,
	0x68, 0x8a, 0x64, 0x0d, 0x65, 0x13, 0x76, 0x1f, 0x50, 0x93, 0xb4, 0xf8, 0x35, 0x23, 0x8b, 0xca,
	0xe1, 0xc4, 0x43, 0x3c, 0xda, 0x29, 0xac, 0x9f, 0xaa, 0x2b, 0x38, 0xe6, 0xc0, 0x06, 0x60, 0x7f,
	0x7b, 0x56, 0xb9, 0xbe, 0xfa, 0xf3, 0x62, 0xf9, 0xf4, 0x1b, 0x62, 0x67, 0x19, 0xff, 0x43, 0xd7,
	0x00, 0x11, 0x7a, 0x1e, 0x59, 0x3c, 0x96, 0x1c, 0xc2, 0xee, 0xe1, 0xdc, 0x8f, 0x1a, 0x94, 0x38,
	0x7d, 0x9c, 0xde, 0x6c, 0xbd, 0xbc, 0x2c, 0x0e, 0xd7, 0xf2, 0xe4, 0xcb, 0x47, 0xcf, 0x07, 0x24,
	0x0a, 0xad, 0xc2, 0x91, 0x46, 0x8b, 0x0e, 0x77, 0x65, 0xf5, 0xee, 0xd5, 0x7f, 0xd2, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x38, 0x16, 0x40, 0x68, 0x34, 0x01, 0x00, 0x00,
}
